### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by martinrotter** [martinrotter/qt5-minimalistic-builds#1]
- [x] Fix hardcoded paths for OpenSSL in *.prl files, for example qnativewifibearer.prl (static msvc 2017 build).
- [x] Fix OpenSSL lib files missing (static msvc build).
- [x] Fix qjp2 plugin missing (static msvc build). This cannot be fixed easily, but can be easily workarounded with `QTPLUGIN` qmake variable.
